# Generated by Django 5.1.3 on 2024-12-05 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0002_membershipplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('book_content', models.FileField(upload_to='book_contents/')),
                ('book_cover', models.ImageField(upload_to='book_covers/')),
            ],
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_isbn', to='librarymsv1.bookcontent'),
        ),
    ]
