# Generated by Django 5.1.3 on 2024-12-05 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0003_bookcontent_alter_authors_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='book_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='books',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='rent_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
