# Generated by Django 5.1.3 on 2024-12-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0013_bookpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpurchase',
            name='invoice_id',
        ),
    ]
