# Generated by Django 5.1.3 on 2024-12-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0014_remove_bookpurchase_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
