# Generated by Django 5.1.3 on 2024-12-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0015_bookcontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='noteworthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='top20',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='writeplace',
            field=models.BooleanField(default=False),
        ),
    ]
