# Generated by Django 5.1.3 on 2024-12-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarymsv1', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='genres',
            field=models.ManyToManyField(related_name='membership_plans', to='librarymsv1.genres'),
        ),
    ]
